### ISSUE TITLE
4.0.1 : fails with project_dir.resolve() - 'str' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by ianw** [ansible/ansible-compat#258]
One of our ansilbe-lint jobs has started failing with 4.0.1.  Last good run with 3.0.2 is [1], failure is [2].  Full traceback is

```
Traceback (most recent call last):
  File "/home/iwienand/programs/openstack-infra/openstack-zuul-jobs/.tox/linters/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/iwienand/programs/openstack-infra/openstack-zuul-jobs/.tox/linters/lib/python3.11/site-packages/ansiblelint/__main__.py", line 266, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/home/iwienand/programs/openstack-infra/openstack-zuul-jobs/.tox/linters/lib/python3.11/site-packages/ansiblelint/__main__.py", line 157, in main
    initialize_options(argv[1:])
  File "/home/iwienand/programs/openstack-infra/openstack-zuul-jobs/.tox/linters/lib/python3.11/site-packages/ansiblelint/__main__.py", line 105, in initialize_options
    options.cache_dir = get_cache_dir(options.project_dir)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iwienand/programs/openstack-infra/openstack-zuul-jobs/.tox/linters/lib/python3.11/site-packages/ansible_compat/prerun.py", line 13, in get_cache_dir
    basename = project_dir.resolve().name.encode(encoding="utf-8")
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'resolve'
```

Note versions of `ansible-lint` (6.4.0) and `ansible` (2.12) didn't change between the two runs, just `ansible_compat`.

[1] https://storage.bhs.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_6e7/881890/1/check/openstack-zuul-jobs-linters/6e77077/job-output.txt
[2] https://storage.gra.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_a9f/881890/1/gate/openstack-zuul-jobs-linters/a9f991b/job-output.txt

**Comment by ianw** [comment]
Looks like `options.project_dir` is a string @ https://github.com/ansible/ansible-lint/blob/73cdc75bf590d4c103aead63cc24e29688715bb1/src/ansiblelint/config.py#L133 and but ansible-compat is looking for a Path object @ https://github.com/ansible/ansible-compat/blob/ff385f6fd6f7d0ee3485f913a9666b1896e1e6de/src/ansible_compat/prerun.py#L7

**Comment by johanneskastl** [comment]
> This is not ansible-compat bug, is just that the consumer (ansible-lint) is using the old APIs. In fact only the main branch of the linter supports the v4 version of compat, all the other will not work with it.
> 
> Pin it down.

Any timeline on when the next release of ansible-lint will be published containing the changes required to work with ansible-compat 4.0.1?

And: This information might have been a good addition to the release notes. :-)

**Comment by ssbarnea** [comment]
@johanneskastl Would you find a pre-release of ansible-lint suitable this week? In fact the change is mentioned in the drafted release notes but they are not visible due to github limitations.

**Comment by johanneskastl** [comment]
> @johanneskastl Would you find a pre-release of ansible-lint suitable this week? In fact the change is mentioned in the drafted release notes but they are not visible due to github limitations.

Hi @ssbarnea I was trying to plan ahead, not trying to urge you.

If there is a pre-release then I can test that, but I would be glad to know when the next stable release is supposed to be released. Did not find the ansible-lint release plan, I thought I had a bookmark for it...

**Comment by rjeffman** [comment]
This is also breaking ansible-lint pre-commit module.
